"""S1/S2/S3: LBBD lower bounds must be valid (never exceed the proven optimum).

Three interacting defects made LBBD emit invalid (too-high) lower bounds and a
fake `gap=0` optimality certificate:

* S1 — the `load_balance` cut added an unconditional `C_max >= max_k
  completion_k` master row (finish times, not load), forcing gap→0 on any
  instance;
* S2 — optimality/no-good cuts were derived from non-proven (TIMEOUT)
  subproblems, whose makespan is an upper bound, not a certificate;
* S3 — the `capacity`/`setup_cost`/`machine_tsp`/`critical_path` cuts discounted
  only processing time in the master row, not the setup/L(S) contribution, so
  reassigning an op relaxed the bound by too little; `critical_path` also used
  the incumbent's realized contention-inflated path.

Fixes: remove the load_balance, capacity, setup_cost, machine_tsp, and
critical_path optimality cuts (each over-claimed the bound); the only optimality
cut kept is a full-assignment no-good emitted solely when every cluster was
proven OPTIMAL. Report the lower bound as the cut-free master relaxation
(unique + capacity with per-lane division for max_parallel, CP-SAT duration
rounding) capped at best_ub, which is a provably valid global lower bound.
"""

from __future__ import annotations

import json
import random
from datetime import UTC, datetime
from pathlib import Path
from uuid import uuid4

import pytest

from synaps.model import (
    Operation,
    Order,
    ScheduleProblem,
    SetupEntry,
    SolverStatus,
    State,
    WorkCenter,
)
from synaps.solvers.cpsat_solver import CpSatSolver
from synaps.solvers.lbbd_hd_solver import LbbdHdSolver
from synaps.solvers.lbbd_solver import LbbdSolver

INSTANCES = Path(__file__).resolve().parent.parent / "benchmark" / "instances"


def _tiny() -> ScheduleProblem:
    return ScheduleProblem.model_validate(
        json.loads((INSTANCES / "tiny_3x3.json").read_text(encoding="utf-8"))
    )


def test_lbbd_does_not_emit_load_balance_cut() -> None:
    """S1: the invalid load_balance cut must no longer be generated by LBBD."""
    result = LbbdSolver().solve(_tiny(), time_limit_s=10, max_iterations=20, random_seed=42)
    cut_kinds = result.metadata["cut_pool"]["kinds"]
    assert cut_kinds is not None
    assert "load_balance" not in cut_kinds, f"load_balance cut still emitted: {cut_kinds}"
    # capacity/critical_path optimality cuts were also removed (S2/S3).
    assert "capacity" not in cut_kinds, f"capacity cut still emitted: {cut_kinds}"
    assert "critical_path" not in cut_kinds, f"critical_path cut still emitted: {cut_kinds}"


def test_lbbd_hd_does_not_emit_load_balance_cut() -> None:
    """LBBD-HD (which lacked even a guard) must also no longer emit it."""
    result = LbbdHdSolver().solve(_tiny(), time_limit_s=10, max_iterations=8, random_seed=42)
    cut_kinds = result.metadata.get("cut_pool", {}).get("kinds", {})
    assert "load_balance" not in cut_kinds, f"load_balance cut still emitted: {cut_kinds}"


def _proven_optimum(problem: ScheduleProblem) -> float | None:
    cpsat = CpSatSolver().solve(
        problem,
        time_limit_s=60,
        num_workers=1,
        auto_greedy_warm_start=False,
        enable_symmetry_breaking=False,
    )
    if cpsat.status is not SolverStatus.OPTIMAL:
        return None
    return float(cpsat.objective.makespan_minutes)


def _random_problem(seed: int) -> ScheduleProblem:
    """Small instance WITH sequence-dependent setups and precedence chains."""
    rng = random.Random(seed)
    states = [State(code=f"s{i}") for i in range(rng.randint(2, 3))]
    machines = [
        WorkCenter(code=f"M{i}", capability_group="G", speed_factor=1.0)
        for i in range(rng.randint(2, 3))
    ]
    setup_matrix: list[SetupEntry] = []
    for wc in machines:
        for a in states:
            for b in states:
                if a.id != b.id and rng.random() < 0.8:
                    setup_matrix.append(
                        SetupEntry(
                            work_center_id=wc.id,
                            from_state_id=a.id,
                            to_state_id=b.id,
                            setup_minutes=rng.randint(2, 15),
                        )
                    )
    orders: list[Order] = []
    ops: list[Operation] = []
    for _ in range(rng.randint(2, 4)):
        order_id = uuid4()
        orders.append(
            Order(id=order_id, external_ref="O", due_date=datetime(2026, 1, 6, tzinfo=UTC))
        )
        prev_op_id = None
        for seq in range(rng.randint(1, 3)):
            k = rng.randint(1, len(machines))
            op = Operation(
                order_id=order_id,
                seq_in_order=seq,
                state_id=rng.choice(states).id,
                base_duration_min=rng.randint(10, 40),
                eligible_wc_ids=rng.sample([m.id for m in machines], k),
                predecessor_op_id=prev_op_id,
            )
            ops.append(op)
            prev_op_id = op.id
    return ScheduleProblem(
        states=states,
        orders=orders,
        operations=ops,
        work_centers=machines,
        setup_matrix=setup_matrix,
        planning_horizon_start=datetime(2026, 1, 1, tzinfo=UTC),
        planning_horizon_end=datetime(2026, 1, 11, tzinfo=UTC),
    )


@pytest.mark.parametrize("instance", ["tiny_3x3.json", "pareto_setup_tradeoff_4op.json"])
def test_lbbd_lower_bound_never_exceeds_optimum_bundled(instance: str) -> None:
    """S1/S2/S3: the reported LBBD lower bound must not exceed the proven optimum."""
    problem = ScheduleProblem.model_validate(
        json.loads((INSTANCES / instance).read_text(encoding="utf-8"))
    )
    optimum = _proven_optimum(problem)
    if optimum is None:
        pytest.skip(f"{instance}: CP-SAT did not prove optimality")
    lbbd = LbbdSolver().solve(problem, time_limit_s=15, max_iterations=20, random_seed=42)
    # The raw per-iteration master bound may legitimately exceed the optimum in
    # nogood-based Benders once proven assignments are excluded; only the
    # reported bound (min of the cut-free relaxation and best_ub) is the
    # meaningful validity invariant, and it is exactly what the S1 fake
    # certificate violated (reported 95 vs optimum 82 on tiny_3x3).
    reported_lb = float(lbbd.metadata["lower_bound"])
    assert reported_lb <= optimum + 1e-6, (
        f"{instance}: reported lower_bound {reported_lb} > proven optimum {optimum}"
    )


def test_lbbd_lower_bound_valid_with_parallel_machine() -> None:
    """S2/S3: the reported bound must stay valid on a max_parallel > 1 machine.

    A machine with two lanes finishes two 10-minute ops in 10 minutes, not 20.
    Before the per-lane division of the master capacity constraint, LBBD
    reported lower_bound = upper_bound = 20 with gap 0.0 on this instance — the
    same fake certificate S1/S2/S3 target — against a proven optimum of 10.
    """
    state = State(code="s")
    wc = WorkCenter(code="M2", capability_group="G", speed_factor=1.0, max_parallel=2)
    o1, o2 = uuid4(), uuid4()
    problem = ScheduleProblem(
        states=[state],
        orders=[
            Order(id=o1, external_ref="O1", due_date=datetime(2026, 1, 6, tzinfo=UTC)),
            Order(id=o2, external_ref="O2", due_date=datetime(2026, 1, 6, tzinfo=UTC)),
        ],
        operations=[
            Operation(
                order_id=o1,
                seq_in_order=0,
                state_id=state.id,
                base_duration_min=10,
                eligible_wc_ids=[wc.id],
            ),
            Operation(
                order_id=o2,
                seq_in_order=0,
                state_id=state.id,
                base_duration_min=10,
                eligible_wc_ids=[wc.id],
            ),
        ],
        work_centers=[wc],
        setup_matrix=[],
        planning_horizon_start=datetime(2026, 1, 1, tzinfo=UTC),
        planning_horizon_end=datetime(2026, 1, 11, tzinfo=UTC),
    )
    optimum = _proven_optimum(problem)
    if optimum is None:
        pytest.skip("CP-SAT did not prove optimality")
    lbbd = LbbdSolver().solve(problem, time_limit_s=15, max_iterations=20, random_seed=42)
    reported_lb = float(lbbd.metadata["lower_bound"])
    assert reported_lb <= optimum + 1e-6, (
        f"parallel machine: reported lower_bound {reported_lb} > proven optimum {optimum}"
    )


@pytest.mark.slow
def test_lbbd_lower_bound_valid_property_setups_and_precedence() -> None:
    """S1/S2/S3: reported LBBD lower bound <= proven optimum on random setups."""
    checked = 0
    for seed in range(40):
        problem = _random_problem(seed)
        optimum = _proven_optimum(problem)
        if optimum is None:
            continue
        checked += 1
        lbbd = LbbdSolver().solve(problem, time_limit_s=10, max_iterations=20, random_seed=42)
        reported_lb = float(lbbd.metadata["lower_bound"])
        assert reported_lb <= optimum + 1e-6, (
            f"seed={seed}: reported LBBD lower_bound {reported_lb} exceeds proven optimum {optimum}"
        )
    assert checked >= 20, f"too few proven-optimum instances to be meaningful: {checked}"
