"""S1: LBBD must not emit the fake-optimality-certificate `load_balance` cut.

The removed `load_balance` cut added an unconditional master row
`C_max >= max_k completion_k` (no y variables), where completion_k was the
incumbent's per-machine finish time. That asserted `C_max >= makespan(incumbent)`
for every assignment, forcing the reported gap to ~0 within 1-2 iterations on
ANY instance (even trivial ones with no precedence and no setups) — a fake
optimality certificate. This test pins that the cut is gone.

IMPORTANT scope (why this file does not assert `lower_bound <= optimum`):
removing `load_balance` is necessary but NOT sufficient for a valid LBBD lower
bound. The remaining optimization cuts also over-claim:
  * `capacity` / `setup_cost` / `machine_tsp` discount only processing time in
    the master row, not the setup contribution (audit S3), and may use a right
    side from a non-proven (TIMEOUT) subproblem (audit S2);
  * `critical_path` uses the incumbent's *realized* longest path — which
    includes machine-contention idle — as the right side, so it over-claims
    even on setup-free instances (empirically: a setup-free precedence instance
    produced a raw master lower bound of 186 against a proven optimum of 141).
A fully valid LBBD lower bound therefore requires the S2 + S3 + critical-path
cut rework; that is tracked as the follow-up. Asserting `lb <= optimum` here
would fail for reasons unrelated to S1, so this file verifies only the S1
mechanism removal.
"""

from __future__ import annotations

import json
from pathlib import Path

from synaps.model import ScheduleProblem
from synaps.solvers.lbbd_hd_solver import LbbdHdSolver
from synaps.solvers.lbbd_solver import LbbdSolver

INSTANCES = Path(__file__).resolve().parent.parent / "benchmark" / "instances"


def _tiny() -> ScheduleProblem:
    return ScheduleProblem.model_validate(
        json.loads((INSTANCES / "tiny_3x3.json").read_text(encoding="utf-8"))
    )


def test_lbbd_does_not_emit_load_balance_cut() -> None:
    """The invalid load_balance cut must no longer be generated by LBBD."""
    result = LbbdSolver().solve(_tiny(), time_limit_s=10, max_iterations=20, random_seed=42)
    cut_kinds = result.metadata["cut_pool"]["kinds"]
    assert cut_kinds, "no cuts generated — the invariant is not exercised"
    assert "load_balance" not in cut_kinds, f"load_balance cut still emitted: {cut_kinds}"


def test_lbbd_hd_does_not_emit_load_balance_cut() -> None:
    """LBBD-HD (which lacked even a guard) must also no longer emit it."""
    result = LbbdHdSolver().solve(_tiny(), time_limit_s=10, max_iterations=20, random_seed=42)
    cut_pool = result.metadata.get("cut_pool", {})
    cut_kinds = cut_pool.get("kinds", {}) if isinstance(cut_pool, dict) else {}
    assert "load_balance" not in cut_kinds, f"load_balance cut still emitted: {cut_kinds}"
